name: Mumu's Blog
author: Mumu
baseurl: "/"
description: Happy Everyday
github: http://www.github.com/arnp
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: 
location: 42°2'16"N   70°12'47"W
# disqus: diqus-username
disqus: 

##Make sure to edit the above fields, especially for disqus.
timezone: Asia/Shanghai
highlighter: rouge
# markdown: redcarpet
redcarpet:
 extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
